// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnemiubnxuaytztsgldr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZW1pdWJueHVheXR6dHNnbGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODkxNTIsImV4cCI6MjA2MDI2NTE1Mn0.JNFg4aerka4Eh-z5bnlVwNhO1Kh86Q5LLDj0Xq10CZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);